import type { InspectionTemplate } from '../types'

// Generated 1:1 from the official workbook:
// "AL FAHD Workers Camp Welfare Inspection Report" — Assessment Questionnaire sheet.
// Section titles and question texts are copied verbatim (including original spelling).
export const accommodation: InspectionTemplate = {
  id: 'accommodation',
  name: 'Labour Accommodation Audit',
  shortName: 'Accommodation',
  description: 'Welfare inspection of workers’ accommodation using the official assessment questionnaire (Sections A–X).',
  questionnaireTitle: 'Group Labor Accommodation',
  sections: [
    {
      letter: "A",
      title: "Facility Design",
      questions: [
        { code: "A1", text: "Do all buildings have numbers, names, and signage as required by NEOM?" },
        { code: "A2", text: "Does the accommodation sign plate include the name of the establishment, supervisor contact information, residential capacity, include the name of the Contractor and associated project(s)?" },
        { code: "A3", text: "Are there any cracks in residential facilities that allow the entry of insects or light?" },
        { code: "A4", text: "Are the floors made of well-known materials like marble, ceramic, tile, wood, or cement?" },
        { code: "A5", text: "Is the structure constructed of appropriate materials in terms of quality and appearance, such as bricks, concrete, aluminum, or portable cabins?\nIs Asbestos-containing material being used?" },
        { code: "A6", text: "Is there an outdoor seating and shade adjacent to each accommodation block?" },
        { code: "A7", text: "All the doors should be fire rated?" },
        { code: "A8", text: "Evacuation procedures should be developed in line with the Civil Defense regulations. Residents must be trained in the evacuation procedures." },
        { code: "A9", text: "Location approved by local municipality for the purposes of Group Accommodation." },
        { code: "A10", text: "The Accommodation must have a prayer room or be placed in close proximity to a mosque to accommodate those who wish to pray." },
        { code: "A11", text: "Are the ambulance number, police number and the municipal report signage prominently displayed?" },
        { code: "A12", text: "Are housing buildings being used as warehouses for any high explosive, flammable, chemical, or hazardous materials?" },
        { code: "A13", text: "Are all accommodation buildings equipped with fire alarms and have mustering points nearby?" },
      ],
    },
    {
      letter: "B",
      title: "Location and Buildings",
      questions: [
        { code: "B1", text: "Accommodation shall be far from unsuitable land within hazardous areas, in flood streams/wadis, areas of historical and archeological significance, or areas of environmental importance or unfit for human habitation, such as nature reserves, agricultural areas, etc. It must be located at no less than one thousand (1,000) meters away from such areas ." },
      ],
    },
    {
      letter: "C",
      title: "Ventilation and Air Conditioning",
      questions: [
        { code: "C1", text: "The apartment/ villa must be ventilated, and air conditioned as per The Standards and conditions adopted by the competent local authority. Air conditioning units must have invertor capabilities to provide cold and warm air. Window ACs (Air Conditioning) are not permitted." },
        { code: "C2", text: "Is there any regular inspection, testing and maintenance schedule in place?" },
      ],
    },
    {
      letter: "D",
      title: "Bathrooms",
      questions: [
        { code: "D1", text: "Are the bathrooms designed and located within the same building as Residents bedrooms?" },
        { code: "D2", text: "Does each common bathroom have a toilet, wash basin, and a shower, at a rate of 1 to 6 residents?" },
        { code: "D3", text: "Are the bathrooms cleaned at least twice (2) daily and more frequently as may be required, by a contracted cleaning company with full cleaning schedules displayed? [logs required to prove this]" },
        { code: "D4", text: "Are the toilet rooms completely isolated from the rest of the house and have an area of at least 1.5 m²?" },
        { code: "D5", text: "Does the area of the shower; including the nozzle, shower head, and door; exceed 120 cm x 80 cm?" },
        { code: "D6", text: "Do the bathrooms have suction fans and lighting?" },
        { code: "D7", text: "Are the bathrooms fully tiled from the floor to the ceiling with non-slip, high-quality, large format tiles that are at least 6 mm thick?" },
        { code: "D8", text: "Does the combination of a shower and toilet is expressly prohibited?" },
        { code: "D9", text: "Toilets and bathrooms include mirrors and fixtures to hang clothes and towels and to place the soap." },
        { code: "D10", text: "Washing machines are not to be used in the bathrooms." },
      ],
    },
    {
      letter: "E",
      title: "Bedrooms",
      questions: [
        { code: "E1", text: "Is the bedroom ceiling height equal to or greater than 3m without plaster or decoration? or equal to or greater than 2.2m with plaster or decorations?" },
        { code: "E2", text: "All doors and windows must be lockable , doors must be fire rated." },
        { code: "E3", text: "Is the maximum number of residents per room 4, while providing adequate space for all residents? Each Resident must be provided with a minimum area of 6m2 per person in a bedroom." },
        { code: "E4", text: "Each bed space must include a privacy screen/curtain." },
        { code: "E5", text: "Is each resident provided with his/her own sleeping area?" },
        { code: "E6", text: "Is there a minimum space of 1m between beds in rooms with multiple beds?" },
        { code: "E7", text: "Are all mattresses, pillows, and duvets/blankets replaced at no cost to the resident every two years?" },
        { code: "E8", text: "Is there any kind of infestation on the furniture and beds?" },
        { code: "E9", text: "Is the each Resident must have a full-length personal closet, inclusive of hanging and shelf space, with the space between the bed and the closet being least 80cm. The closet must have a functioning lock?" },
        { code: "E10", text: "Each Resident must be provided with a bedside table and a reading lamp." },
        { code: "E11", text: "Each Resident is to be provided with a personal lock box and key for storage of small items and valuables, in addition to the closet and bedside table." },
        { code: "E12", text: "Are smoke detectors installed in every bedroom, and are they tested on a every month and Contractor must maintain a testing log?" },
        { code: "E13", text: "Are intact mesh window screens provided for openings to prevent the entry of insects?" },
        { code: "E14", text: "Are the windows provided equipped with black-out blinds and curtains?" },
        { code: "E15", text: "Each bedroom must be equipped with a water dispenser, a fridge, a kettle, with four (4) cups?" },
        { code: "E16", text: "A small table and chairs must be provided in each bedroom." },
        { code: "E17", text: "Each Resident should have access to two electrical sockets and extension leads will not be used." },
        { code: "E18", text: "Accommodation information signs including emergency evacuation routes and emergency contact details must be displayed on the back of every door in a language the residents understand." },
        { code: "E19", text: "Are there shoe racks provided and placed at each bedroom's entrance?" },
      ],
    },
    {
      letter: "F",
      title: "Kitchens (Catered and Self-Cooking)",
      questions: [
        { code: "F1", text: "Are caterers hired to manage/ operate the kitchens and canteens in this accommodation facility?" },
        { code: "F2", text: "Is the kitchen run by a licensed food service company or by professional caterers?" },
        { code: "F3", text: "Does the on-site catered food adhere to all KSA food safety regulations?\n[obtain certification proof]" },
        { code: "F4", text: "Do the catered kitchen facilities come with the accommodation?" },
        { code: "F5", text: "Do the Kitchen employees have valid health certificates?" },
        { code: "F6", text: "Are the food preparation, serving, and counter areas, as well as the shelves, made of stainless steel or glass?" },
        { code: "F7", text: "Do the employees in the kitchens wear clean uniforms during service hours?" },
        { code: "F8", text: "Is there permanent natural ventilation provided inside the kitchen with a window to the open air protected by a fine metal mesh and an appropriate air suction cup?" },
        { code: "F9", text: "Does the food provided to individuals contain the basic materials required by the body, such as proteins, sugars, fats, vitamins, and minerals, and does the result of eating three daily meals not fall below 3500 calories?" },
        { code: "F10", text: "Are toilets, kitchens, and dining halls cleaned twice daily, and also using disinfectants at least once a week, and under the supervision of a specialized technician?" },
      ],
    },
    {
      letter: "G",
      title: "Self-Cooing Section",
      questions: [
        { code: "G1", text: "Is the accomodation site been provided with self-catering facilities?" },
        { code: "G2", text: "Is there a clean and functional kitchen with a functioning cooking stove (electric or gas) and cooling equipment?" },
        { code: "G3", text: "Is the kitchen larger than 1.5m by 1m and large enough for 25% of the total residents to prepare and cook meals?" },
        { code: "G4", text: "Does the kitchen have one stainless-steel basin for washing utensils and tools for every five people in the kitchen's total capacity?" },
        { code: "G5", text: "Are all food preparation, serving, counter, and shelf surfaces made of stainless steel or glass?" },
        { code: "G6", text: "Is there a separate warehouse with shelves for storing foodstuffs or kitchen cupboards for transporting, storing, and circulating foodstuffs, such as temperature, humidity, and storage means?" },
        { code: "G7", text: "Are there enough washbasins and fresh water taps with a sufficient flow provided?" },
        { code: "G8", text: "Is kitchen liquid waste disposed of properly through a sewerage system?" },
        { code: "G9", text: "Is the kitchen floor tiled?" },
        { code: "G10", text: "Are the floor and walls made of smooth, easy-to-clean materials, and are the floors equipped with a drain that adequately protects against rodent and insect entry?" },
        { code: "G11", text: "Are the kitchens cleaned twice a day and disinfectants used at least once a week while being overseen by a specialized technician?" },
        { code: "G12", text: "Is there permanent natural ventilation provided inside with a window to the open air in a suitable area protected by a fine metal mesh and an air suction cup?" },
        { code: "G13", text: "Are the kitchen windows and catering areas protected from rodents and insects by tiny mesh screens?" },
        { code: "G14", text: "Is a contract in place with a company to clean, disinfect, and sanitize residential units and facilities (kitchens) (contract should be in place at least once every three months) (proof of contract)?" },
        { code: "G15", text: "Is the external kitchen door (if any) equipped with a tiny mesh screen and air curtains to keep insects out?" },
        { code: "G16", text: "Do suction fans come with each kitchen?" },
        { code: "G17", text: "Is there an adequate supply of insect traps for each kitchen?" },
        { code: "G18", text: "Is there a pair of carbon dioxide fire extinguishers in each kitchen?" },
        { code: "G19", text: "Are there containers for collecting food waste that are tightly sealed?" },
        { code: "G20", text: "Are the meals served in hygienic stainless steel or disposable utensils and dishes?" },
        { code: "G21", text: "Do kitchen workers wear proper personal protective equipment (e.g., hair covers, shoe covers, and gloves) for safety and hygiene reasons?" },
        { code: "G22", text: "Are the kitchens equipped with air extractors to remove vapours, odors, and heat?" },
      ],
    },
    {
      letter: "H",
      title: "Mess and Dining Facilities",
      questions: [
        { code: "H1", text: "A dedicated room must be provided for dining purposes." },
        { code: "H2", text: "All dining hall facilities must be equipped with sufficient seating space for Residents to comfortably eat their meals and be kept clean at all times." },
        { code: "H3", text: "Is there sufficient number of insect traps provided for all dining halls?" },
        { code: "H4", text: "Is there a suitable handwashing station equipped with soap and disinfectants in dining halls?" },
        { code: "H5", text: "Is the surface of food preparation tables made of steel?" },
        { code: "H6", text: "Pest control must be undertaken once (1) a week in all mess/dining hall areas, with records available and submitted to the Worker Welfare Team on a monthly basis." },
        { code: "H7", text: "Dining halls shall be designed to allow for natural light and ventilation as per SBC requirements." },
        { code: "H8", text: "Sufficient air conditioning shall be provided to cool a fully occupied room during the hottest periods." },
      ],
    },
    {
      letter: "I",
      title: "Leisure and General Facilities",
      questions: [
        { code: "I1", text: "Are there sufficient communal areas provided both outdoor and indoor? Outdoor communal spaces must include shaded areas and seating/gathering areas?" },
        { code: "I2", text: "The Contractor shall provide a TV set for Residents with channels tailored to the needs of Residents." },
        { code: "I3", text: "Is there a High speed open internet services must be provided free of charge in accordance with NEOM service provider’s highest operating service with wireless access throughout the Accommodation, including in external recreational areas? Wi-Fi will be provided free of charge to all Workers." },
        { code: "I4", text: "Is there access to local stores not be more than ten (10) minutes by foot and be easily accessible?" },
        { code: "I5", text: "Designated external smoking areas must be provided to the exterior of the building, smoking is not prohibited within the building." },
      ],
    },
    {
      letter: "J",
      title: "Laundry Services",
      questions: [
        { code: "J1", text: "The Contractor shall ensure that free of charge laundry services or facilities are provided to Residents and Accommodation staff for work uniforms/overalls twice (2) per week, bed linen once (1) per week and towels once (1) per week." },
        { code: "J2", text: "Self Service laundry facilities should be provided free of charge with all the required services such as hot and cold-water connections, ventilation and air conditioning, drainage system, laundry detergent and sufficient lighting." },
        { code: "J3", text: "Drying racks are to be provided, where communal laundry is provided." },
      ],
    },
    {
      letter: "K",
      title: "Lightning",
      questions: [
        { code: "K1", text: "Do all rooms in the residential units have working lights?" },
        { code: "K2", text: "Is there a complete indoor lighting system for the indoor spaces?" },
        { code: "K3", text: "All stairways, corridors and passageways that lead to the public ways must be equipped with emergency lighting and illuminated wayfinding to provide initial illumination that is not less than an average of eleven (11) lux and, at any point, not less than one (1) lux, measured along the path of egress at floor level." },
        { code: "K4", text: "Emergency lighting must be available for ninety (90) minutes immediately after the power failure in accordance with SBC 801 and must consist of storage batteries unit equipment installed in a centralized or distributed way ." },
        { code: "K5", text: "Maintenance records shall be maintained and readily available for inspection upon request." },
      ],
    },
    {
      letter: "L",
      title: "Sanitary Drainage",
      questions: [
        { code: "L1", text: "Do all buildings and outdoor features have grading, drainage, and stormwater management systems (including swales, ditches, piping, and manholes)?" },
      ],
    },
    {
      letter: "M",
      title: "Water Supply System",
      questions: [
        { code: "M1", text: "Are chilled drinking water fountains provided in all public areas?" },
        { code: "M2", text: "The water systems are installed, operated and maintained to prevent the growth of bacteria and other air carried microbes, as per the local authority and the Laws and regulations of the Kingdom of Saudi Arabia ." },
        { code: "M3", text: "Water storage systems shall be regularly tested for legionella and treated where legionella is found to be present." },
      ],
    },
    {
      letter: "N",
      title: "Hot and Cold-Water Supply",
      questions: [
        { code: "N1", text: "Is the water distribution for domestic services pressurized, regulated, and maintained throughout the building to meet acceptable levels?\n[Minimum 175 kPa and maximum 475 kPa at water outlets]" },
        { code: "N2", text: "Is the domestic hot water provided to the entire bathrooms, showers, kitchens, and laundry sinks?" },
        { code: "N3", text: "Is the stored water for domestic use provided with proper chlorination system and equipped with sand filters?" },
      ],
    },
    {
      letter: "O",
      title: "Drinking Water",
      questions: [
        { code: "O1", text: "Drinking water shall be provided, free of charge, in sufficient quantities from a secure health source, whether through public or other network, and shall be fit for human consumption and conforming with Saudi Standard Specifications No. (701/2000M) pertaining to potable water." },
        { code: "O2", text: "Chilled drinking water fountains must be provided in all public areas." },
        { code: "O3", text: "Water tanks in communal areas must be well maintained, in a clean condition and properly covered. Cleaning and sanitizing the floor and upper water tanks at least once a year and maintain a proof of the same ." },
        { code: "O4", text: "Laboratory analysis of water must be carried out at least once (1) a year by laboratories approved by NEOM to check its safety for human consumption. Contractors must keep a record of water analysis ." },
        { code: "O5", text: "Water coolers must be placed in every bedroom, with cups available for each Resident." },
        { code: "O6", text: "Testing certificates must be provided monthly to the NEOM Worker Welfare Team." },
      ],
    },
    {
      letter: "P",
      title: "Electricity Supply",
      questions: [
        { code: "P1", text: "Are the safety requirements met according to the instructions of the Civil Defense? [such as the availability of sufficient numbers of fire extinguishers and other requirements]" },
        { code: "P2", text: "Electrical rooms must be provided with two (2) hour rated enclosure with portable fire extinguishers." },
        { code: "P3", text: "Electricity sockets must be intact and firmly covered with no apparent or exposed wires." },
        { code: "P4", text: "Access to all electrical boxes/panels must be unobstructed." },
        { code: "P5", text: "Provision of electrical outlets must be adequate for the number of people and must not at any time be at risk of overloading." },
        { code: "P6", text: "A documented maintenance schedule shall be established and adhered to, ensuring regular inspections and testing of all electrical systems by a qualified electrician. Testing must include Portable Appliance Testing (PAT) to ensure the safety of electrical appliances and installations within accommodation at no cost to Workers." },
        { code: "P7", text: "A documented emergency plan shall be established and readily available to all Workers, clearly outlining procedures to follow in the event of an electrical failure." },
      ],
    },
    {
      letter: "Q",
      title: "Gas Supply",
      questions: [
        { code: "Q1", text: "The LPG system installed for the accommodation shall complies with the below requirements:\nIs the LPG plant located in a designated plot?" },
        { code: "Q2", text: "Is the LPG plant site designed to prevent any unauthorized access? and there is a sufficient space for all routine maintenance activities?" },
        { code: "Q3", text: "Is the LPG plant area fenced ?" },
        { code: "Q4", text: "Is the LPG plant area illuminated by flood lamps installed at high level?" },
        { code: "Q5", text: "Are all the separations between equipments, tanks, and adjacent buildings or routes comply with NFPA 58?" },
        { code: "Q6", text: "Is the LPG plant equipped with gas detectors and transmitters to shut the supply valves in case of a gas leak?" },
      ],
    },
    {
      letter: "R",
      title: "Firefighting Systems, Alarms, and Public Address Systems",
      questions: [
        { code: "R1", text: "An automatic fire alarm system shall be installed and monitored from within the Accommodation by means of an automatic fire alarm panel, which must be installed in secure places such as the security offices on the ground floor." },
        { code: "R2", text: "Fire detection systems must be available in each bedroom, as per KSA Fire Life Safety Code of Practice." },
        { code: "R3", text: "A public announcement system must be installed in every accommodation." },
      ],
    },
    {
      letter: "S",
      title: "Firefighting Equipment and Emergency Exits",
      questions: [
        { code: "S1", text: "Firefighting equipment and emergency exits must be provided in accordance with local regulatory requirements to effectively assist in the fighting of any outbreak of fire and to expedite the successful evacuation of residents from an area where fire the has broken out." },
        { code: "S2", text: "All buildings must be equipped with fire detection, smoke detection, suppression, protection equipment, signage, warnings as per NFPA requirements." },
        { code: "S3", text: "The main passages and apartments of the facility must be equipped with hose reels and fire extinguishers." },
        { code: "S4", text: "Fire detection systems must include fire detectors like smoke and heat detectors and manual fire alarm boxes." },
        { code: "S5", text: "Emergency wayfinding and evacuation plans must be readily available in a language the Workers understand." },
        { code: "S6", text: "Fire drills must be undertaken every four (4) months." },
        { code: "S7", text: "Fully trained and certified fire wardens must be appointed and live physically in each building – details of fire wardens and contact details must be displayed on every floor." },
        { code: "S8", text: "Any fire related incidents occurring in an Accommodation must be reported to the NEOM Worker Welfare Team within a maximum of twenty-four (24) hours, accompanied by a full report with findings and recommendations." },
        { code: "S9", text: "Call points that activate the fire alarm system shall be available within the accommodation facility." },
      ],
    },
    {
      letter: "T",
      title: "Medical Services",
      questions: [
        { code: "T1", text: "First aid kits are available in the Accommodation, at least one (1) in each apartment or at least one (1) for up to ten (10) people and one (1) per floor in the case of villa; all first aid kits are to be adequately stocked." },
        { code: "T2", text: "Contractors must have a medical emergency response plan that includes contagious disease outbreak." },
        { code: "T3", text: "Contractors must have at least one (1) certified first aider available for every fifty (50) residents." },
        { code: "T4", text: "Accommodation must not be located more than a twenty (20) minute drive from a medical facility/clinic." },
        { code: "T5", text: "Medical incidents of any form must be reported in writing to the Worker Welfare Team, within four (4) hours of the incident occurring." },
        { code: "T6", text: "Contractors must hold an adequate stock of face masks and hand sanitizers for Residents, available on request, at no charge to the Residents." },
        { code: "T7", text: "A qualified health care practitioner with a certificate in handling first aid materials and fast-tracking measurement equipment, such as thermometers, must be present in the first aid room at all times." },
        { code: "T8", text: "Availablity of emergency vehicle?" },
      ],
    },
    {
      letter: "U",
      title: "Public Health Hazards",
      questions: [
        { code: "U1", text: "All necessary and effective measures must be implemented to prevent public health hazards such as insects and rodents from existing or multiplying in or around the Accommodation." },
        { code: "U2", text: "A company specializing in controlling public health hazards and licensed by the competent local authority is contracted to carry out pest control/extermination activities at a minimum of once (1) per month." },
        { code: "U3", text: "Records and reports of completed extermination activities must be kept including treatment for bed bugs." },
      ],
    },
    {
      letter: "V",
      title: "Waste Disposal",
      questions: [
        { code: "V1", text: "Waste from apartments/villas must be removed daily." },
        { code: "V2", text: "Closed and washable waste bins must be provided in sufficient quantities and kept clean." },
        { code: "V3", text: "Contractors must clean and maintain all residential facilities either themselves or through contract with an operation and maintenance company and submit proof of the same." },
        { code: "V4", text: "Waste Management contracts must be available for inspection and provided to the Worker Welfare Team upon request." },
      ],
    },
    {
      letter: "W",
      title: "Accommodation Management",
      questions: [
        { code: "W1", text: "An Accommodation Manager or any other responsible person must be appointed to manage all the facilities. If a third-party service provider is being used, clear contractual management responsibilities and reporting requirements must be established." },
        { code: "W2", text: "The Accommodation Manager or any other responsible person must maintain a register of the residents in the Accommodation within a database." },
        { code: "W3", text: "Residents must not have any restrictions of movements places on them in terms of leaving the accommodation (unless mandated by law / national curfew / defined temporary safety restrictions). Further, residents are not required to request permission to leave the accommodation from their managers / supervisors." },
        { code: "W4", text: "The Accommodation Manager or any other responsible person is responsible for: \ni.\tCoordinating regular inspection of all Accommodations. \nii.\tControlling and managing the planned occupation percentage against actual occupation (population density). \niii.\tIssuing instructions and following up on; onsite maintenance, food activities and nutrition, utilities management, ensuring observance of housing instructions by all the residents, managing inspection activities and corrective actions, managing the housing budget, organizing and holding periodic training sessions on evacuation in case of emergency (e.g., fire, medical, etc.), and supervising the introductory training program. \niv.\tReporting to the Ministry of Health and NEOM Worker Welfare team, the eruption of any contagious diseases, food poisoning and other important casualties." },
      ],
    },
    {
      letter: "X",
      title: "Health, Safety and Security",
      questions: [
        { code: "X1", text: "The Contractor must prepare a fire safety plan, which must include training of fire marshals, periodic inspections, testing and maintenance of fire safety equipment, fire safety inspections and drills." },
        { code: "X2", text: "The Contractor must provide security surveillance cameras linked to the NEOM Operational Command Center." },
        { code: "X3", text: "Licensed security guards must be provided for the Accommodation." },
        { code: "X4", text: "Each Resident, within one (1) week from the checking into the Accommodation must attend an awareness program that covers the following topics: \ni.\tInstructions for the unit management/residential compound. \nii.\tHouse rules. \niii.\tProper use of services and facilities, recreational activities. \niv.\tPersonal hygiene. \nv.\tDiseases. \nvi.\tWaste disposal. \nvii.\tPreventing pollution. \nviii.\tPest control. \nix.\tFire prevention and proper use of firefighting equipment. \nx.\tResponsibilities during emergencies. \nxi.\tCopies of the house rules, in a language understood by all the residents, and must be displayed in every apartment of the Accommodation." },
        { code: "X5", text: "The house rules must include, as a minimum, the following topics: \ni.\tCleanliness. \nii.\tProhibitions (smoking, cooking, shisha). \niii.\tUse of storage facilities. \niv.\tWaste disposal. \nv.\tMusic.\nvi.\tTampering with the building equipment. \nvii.\tWater preservation. \nviii.\tVisitors. \nix.\tAny other matter deemed necessary by the Accommodation Manager or any other person responsible. \nx.\tThe Residents, staff and visitors must not be permitted to use tobacco products inside the Accommodation. Suitable signage must be posted around the Accommodation to ensure strict enforcement.  \nxi.\tThe use of tobacco products must be permitted outdoors or in designated smoking areas that are completely isolated from non‐smoking areas." },
      ],
    },
  ],
}
