import type { WalkthroughArea } from '../types'

// Generated from "Camp_Inspection_Walkthrough_Framework.xlsx" — the inspector's
// area-by-area walkthrough. Each line is a quick reminder mapped to official
// questionnaire codes; answering a line answers all of its mapped questions.
export const accommodationWalkthrough: WalkthroughArea[] = [
  {
    title: "Camp Entrance & Exterior",
    lines: [
      { codes: ["A2"], label: "Sign plate at entrance: camp name, supervisor contact, capacity, contractor name" },
      { codes: ["A1"], label: "All buildings numbered / named with NEOM-required signage" },
      { codes: ["A11"], label: "Ambulance, police & municipality numbers displayed prominently" },
      { codes: ["X3"], label: "Licensed security guards present at gate" },
      { codes: ["X2"], label: "CCTV cameras working & linked to NEOM Operational Command Center" },
      { codes: ["A6"], label: "Outdoor seating + shade next to each accommodation block" },
      { codes: ["A13"], label: "Fire alarm on buildings; mustering point signed & nearby" },
      { codes: ["I5"], label: "Designated external smoking area (no smoking inside)" },
      { codes: ["U1"], label: "No stagnant water, junk piles or clutter around buildings & side passages" },
      { codes: ["L1"], label: "Site drainage OK - no ponding, blocked drains or flood risk" },
      { codes: ["V2"], label: "Closed, washable waste bins outside - sufficient & clean; waste removed daily" },
      { codes: ["Q1", "Q2", "Q3", "Q4", "Q5", "Q6"], label: "LPG: cylinders/tank OUTSIDE, fenced, ventilated, gas detectors, NFPA 58 spacing - never indoors" },
    ],
  },
  {
    title: "Corridors, Stairs & Common Circulation",
    lines: [
      { codes: ["K3"], label: "Emergency lighting on all stairways, corridors & exits" },
      { codes: ["S1", "S2"], label: "Emergency exits clear, unobstructed & signed" },
      { codes: ["S3"], label: "Extinguishers + hose reels wall-mounted, tagged, monthly inspection" },
      { codes: ["S4", "S9"], label: "Smoke/heat detectors + manual call points in passages" },
      { codes: ["S5", "E18"], label: "Evacuation plan posted (in workers' language); route signage" },
      { codes: ["R1", "R3"], label: "Fire alarm panel monitored; PA/announcement system working" },
      { codes: ["A3"], label: "No cracks letting in insects or light; general repair condition" },
      { codes: ["K1", "K2"], label: "All lights working indoors & outdoors" },
    ],
  },
  {
    title: "Bedrooms",
    lines: [
      { codes: ["E3"], label: "Max 4 residents/room, min 6 m² per person" },
      { codes: ["E6"], label: "Min 1 m spacing between beds" },
      { codes: ["E4"], label: "Privacy screen/curtain for EVERY bed space" },
      { codes: ["E5", "E7"], label: "Own bed & bedding per resident - condition, replaced every 2 years (E7)" },
      { codes: ["E8"], label: "No infestation / bed bugs on furniture & beds" },
      { codes: ["E9", "E11"], label: "Full-length closet each + 80 cm clearance; personal lock box (E11)" },
      { codes: ["E10"], label: "Bedside table + reading lamp each resident" },
      { codes: ["E15", "O5"], label: "Water dispenser/cooler, fridge, kettle + cups in room" },
      { codes: ["E16"], label: "Small table & chairs in room" },
      { codes: ["E17"], label: "2 sockets per resident, intact, no extension leads" },
      { codes: ["E12"], label: "Smoke detector in every bedroom (tested monthly - see log)" },
      { codes: ["E13", "E14"], label: "Window mesh screens intact; blackout blinds/curtains" },
      { codes: ["E2", "A7"], label: "Door & windows lockable; doors fire-rated" },
      { codes: ["E18"], label: "Evacuation route + emergency contacts on back of door" },
      { codes: ["E19"], label: "Shoe rack at entrance" },
      { codes: ["C1"], label: "AC working, no leaks, filters clean" },
      { codes: ["E1"], label: "Ceiling height ≥3 m (or ≥2.2 m with false ceiling)" },
    ],
  },
  {
    title: "Bathrooms & Toilets",
    lines: [
      { codes: ["D2"], label: "Ratio: 1 toilet + basin + shower per 6 residents" },
      { codes: ["D1"], label: "Located in same building as bedrooms" },
      { codes: ["D8"], label: "Shower & toilet NOT combined in one compartment" },
      { codes: ["D4"], label: "Toilet fully isolated, area ≥1.5 m²" },
      { codes: ["D5"], label: "Shower size >120 x 80 cm" },
      { codes: ["D7"], label: "Tiled floor-to-ceiling, non-slip, good condition" },
      { codes: ["D6"], label: "Exhaust fan + lighting working" },
      { codes: ["D3"], label: "Cleaned 2x daily by cleaning company - schedule displayed" },
      { codes: ["D9"], label: "Mirrors, clothes/towel hooks, soap holders" },
      { codes: ["D10"], label: "No washing machines in bathrooms" },
      { codes: ["N2"], label: "Hot water available at showers & basins" },
    ],
  },
  {
    title: "Kitchen (Catered / Self-Cooking)",
    lines: [
      { codes: ["F1", "F2", "F3"], label: "Caterer licensed + KSA food safety certificates (if catered)" },
      { codes: ["G2"], label: "Working stoves + cooling equipment, clean & functional" },
      { codes: ["G5", "F6"], label: "Prep surfaces, counters & shelves stainless steel/glass" },
      { codes: ["G4"], label: "1 washing basin per 5 users, fresh water taps" },
      { codes: ["G6"], label: "Food storage: labelled, covered, off floor, temperature controlled; fridges/freezers CLEAN" },
      { codes: ["G12", "G13", "G16"], label: "Ventilation + fine mesh on windows/doors; suction fans (G16)" },
      { codes: ["G17"], label: "Insect traps adequate" },
      { codes: ["G18"], label: "2x CO2 extinguishers in kitchen" },
      { codes: ["G19"], label: "Food waste in tightly sealed containers - nothing stored on cabinet tops" },
      { codes: ["G11"], label: "Cleaned 2x daily + weekly disinfection (check it looks it)" },
      { codes: ["Q1"], label: "NO LPG cylinders inside the kitchen" },
      { codes: ["G21", "F7", "F5"], label: "Staff PPE: hair cover, gloves, clean uniforms; health certificates (F5)" },
      { codes: ["G8", "G9", "G10"], label: "Liquid waste to sewerage; floor tiled with drain, rodent-proofed (G10)" },
    ],
  },
  {
    title: "Dining / Mess Hall",
    lines: [
      { codes: ["H1", "H2"], label: "Dedicated dining room, enough clean seating for shift" },
      { codes: ["H4"], label: "Handwash station with soap/disinfectant at entrance" },
      { codes: ["H5"], label: "Food serving/prep tables steel surface" },
      { codes: ["H3"], label: "Insect traps sufficient" },
      { codes: ["H6"], label: "Weekly pest control - ask for records" },
      { codes: ["H7", "H8"], label: "Natural light + ventilation; AC copes when full" },
      { codes: ["F9"], label: "Menu balanced (protein, veg, fruit); food quality/quantity feedback" },
    ],
  },
  {
    title: "Living / Leisure Areas",
    lines: [
      { codes: ["I1"], label: "Indoor + outdoor communal areas; outdoor shaded with seating" },
      { codes: ["I2"], label: "TV with channels suited to residents" },
      { codes: ["I3"], label: "Free high-speed internet/Wi-Fi working - test it" },
      { codes: ["I4"], label: "Shops/groceries within 10 min walking" },
      { codes: ["A10"], label: "Prayer room or mosque close by" },
      { codes: ["E12"], label: "Smoke detectors in communal rooms" },
    ],
  },
  {
    title: "Laundry",
    lines: [
      { codes: ["J1"], label: "Free laundry service OR self-service facilities" },
      { codes: ["J2"], label: "Machines working, hot & cold water, powder available" },
      { codes: ["J3"], label: "Drying racks provided (not on railings/windows)" },
      { codes: ["D10"], label: "No washing machines in bathrooms" },
    ],
  },
  {
    title: "Utilities & Electrical",
    lines: [
      { codes: ["P3"], label: "Sockets intact, covered, NO exposed wires anywhere" },
      { codes: ["P4"], label: "DB panels labelled, closed, access unobstructed" },
      { codes: ["P2"], label: "Electrical rooms: 2-hr rated enclosure + extinguisher, no storage inside" },
      { codes: ["P5"], label: "No overloading / extension leads daisy-chained" },
      { codes: ["K4"], label: "Emergency lighting lasts 90 min - ask for test records" },
      { codes: ["N1", "N3"], label: "Water pressure OK; chlorination + sand filters on stored water" },
      { codes: ["M2"], label: "Tanks & water systems maintained - clean, covered, no leaks" },
    ],
  },
  {
    title: "Drinking Water",
    lines: [
      { codes: ["O1", "O2", "M1"], label: "Free drinking water; chilled fountains in all public areas (M1)" },
      { codes: ["O5"], label: "Water cooler + cups in every bedroom" },
      { codes: ["O3"], label: "Tanks clean, covered; cleaning/sanitizing records" },
      { codes: ["M3"], label: "Legionella testing done - ask for results" },
      { codes: ["O4"], label: "Annual lab analysis by NEOM-approved lab - ask for certificate" },
      { codes: ["O6"], label: "Monthly test certificates sent to NEOM WW team" },
    ],
  },
  {
    title: "Medical & First Aid",
    lines: [
      { codes: ["T1"], label: "First aid kits: 1 per apartment / per 10 residents, stocked & in date" },
      { codes: ["T3"], label: "Certified first aider: min 1 per 50 residents - ask for certificate" },
      { codes: ["T2"], label: "Medical emergency response plan incl. disease outbreak" },
      { codes: ["T6"], label: "Stock of face masks + hand sanitizers" },
      { codes: ["T7"], label: "Qualified health practitioner arrangement" },
      { codes: ["T4", "T8"], label: "Clinic within 20 min drive; emergency vehicle available" },
      { codes: ["T5"], label: "Medical incidents reported to WW team within 4 hrs" },
    ],
  },
  {
    title: "Fire Safety (Whole camp)",
    lines: [
      { codes: ["R1"], label: "Automatic fire alarm system, monitored on site" },
      { codes: ["R2", "E12"], label: "Detectors in every bedroom + common areas" },
      { codes: ["S3"], label: "Extinguishers & hose reels: mounted, signed, tagged, in date" },
      { codes: ["S9"], label: "Manual call points available & accessible" },
      { codes: ["S6"], label: "Fire drills every 4 months - ask for records" },
      { codes: ["S7"], label: "Certified fire warden living in each building - names displayed" },
      { codes: ["A8"], label: "Residents trained on evacuation procedure" },
      { codes: ["S8"], label: "Fire incidents reported to WW team within 24 hrs" },
    ],
  },
  {
    title: "Office / Documentation (Ask The Camp Manager)",
    lines: [
      { codes: ["W1"], label: "Accommodation Manager appointed & present - name/contact displayed" },
      { codes: ["W2"], label: "Resident register up to date (names, rooms, check-in/out)" },
      { codes: ["W4"], label: "Accommodation management plan: inspections, cleaning, maintenance duties" },
      { codes: ["X5"], label: "House rules displayed (cleanliness, prohibitions, safety…)" },
      { codes: ["X4"], label: "Induction/awareness records for every resident within 1 week of check-in" },
      { codes: ["X1"], label: "Fire safety plan (wardens, inspections, testing, drills)" },
      { codes: ["E12"], label: "Smoke detector monthly testing log" },
      { codes: ["C2"], label: "AC inspection/testing/maintenance schedule" },
      { codes: ["P6"], label: "Electrical maintenance & inspection schedule + records" },
      { codes: ["K5"], label: "Lighting/emergency lighting maintenance records" },
      { codes: ["M3", "O4", "O6"], label: "Water test results: legionella, annual lab analysis, monthly certificates" },
      { codes: ["U2", "U3"], label: "Licensed pest control company contract + extermination records incl. bed bugs" },
      { codes: ["G14", "V3", "V4"], label: "Cleaning & sanitizing contract for units and kitchens; waste contract (V4)" },
      { codes: ["E7"], label: "Bedding replacement records (every 2 years)" },
      { codes: ["F3", "F5"], label: "Caterer license, food safety certs, kitchen staff health certificates" },
      { codes: ["P7"], label: "Emergency plan available to workers in their language" },
      { codes: ["W3"], label: "No movement restrictions on residents" },
    ],
  },
]
